### ISSUE TITLE
issue-1-see-car 

### ISSUE THREAD

**Issue by hannahnengel** [hannahnengel/m2-0122-code-solutions#8]
## Feature
User can see their car.

## 💰 Motivation
The user needs to see what they will be controlling.

## 📐 Plan
Put a top-down image of a car on the page.

## ✅ Task List
- [ ] Create the html outline and drop in the image of the car that will be used 
- [ ] Style the car and user interface of the game using CSS
- [ ] Ensure the user can see their car
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.

## 🖼 Wireframes 
<img width="860" alt="Feature 1" src="https://user-images.githubusercontent.com/90408240/151883577-7a1b9965-9f75-44bb-8cd3-72efa5b28f93.png">
